(function(){"use strict";
const data=window.NEXTGEN_SERVICE_CATALOG||{categories:[],services:[]};
const homeCategories=data.categories||[],homeServices=data.services||[];
const catalogCategories=data.catalogCategories||homeCategories,catalogServices=data.catalogServices||homeServices;
const homeCategoryMap=Object.fromEntries(homeCategories.map(x=>[x.slug,x]));
const catalogCategoryMap=Object.fromEntries(catalogCategories.map(x=>[x.slug,x]));
const categoryFor=(s,map)=>map[s.category]||{label:"Custom Service"};
const matchesCategory=(s,slug)=>!slug||s.category===slug||(s.secondaryCategories||[]).includes(slug);
const quoteFor=s=>"/?service="+encodeURIComponent(s.slug)+"#contact";
const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
const categoryIcons={"ai-automation":"sparkles","ai-llm":"sparkles","business-automation":"sparkles","ai-model-engineering":"sparkles",websites:"panels-top-left","web-saas":"panels-top-left","software-apis":"code-xml","software-backend":"code-xml","api-integrations":"code-xml","data-scraping":"code-xml","bots-messaging":"code-xml",trading:"chart-no-axes-combined","trading-systems":"chart-no-axes-combined","cloud-support":"cloud","cloud-devops":"cloud"};
const icon=name=>'<svg class="sf-icon" aria-hidden="true" focusable="false"><use href="/assets/ui-icons.svg?v=1#'+name+'"></use></svg>';
const iconFor=category=>icon(categoryIcons[category]||"code-xml");
const card=(s,map)=>{const c=categoryFor(s,map),q=quoteFor(s),published=!!(s.href&&s.published!==false),href=published?s.href:q,title=escapeHtml(s.title),action=published?'<a href="'+escapeHtml(s.href)+'" aria-label="View '+title+'">View service</a>':'<a href="'+escapeHtml(q)+'" aria-label="Discuss '+title+'">Discuss service</a>';return '<article class="sf-service-card"><a class="sf-service-main" href="'+escapeHtml(href)+'"><div class="sf-card-thumb" aria-hidden="true"><span>'+iconFor(s.category)+'</span><i>'+escapeHtml(s.thumb||"NG")+'</i></div><span class="sf-card-category">'+escapeHtml(c.label)+'</span><h3>'+title+'</h3><p>'+escapeHtml(s.description)+'</p><small>'+escapeHtml(s.meta)+'</small></a><div class="sf-service-actions">'+action+'<a class="sf-quote-link" href="'+escapeHtml(q)+'" aria-label="Request a quote for '+title+'">Request a quote</a></div></article>'};
function renderCategories(){document.querySelectorAll("[data-storefront-categories]").forEach(root=>root.innerHTML=homeCategories.map(c=>'<a class="sf-category-card" href="'+escapeHtml(c.url)+'"><div class="sf-category-icon">'+iconFor(c.slug)+'</div><span>'+escapeHtml(c.label)+'</span><p>'+escapeHtml(c.short)+'</p><b>Explore '+icon("arrow-right")+'</b></a>').join(""))}
function renderFeatured(){const root=document.getElementById("featured-services-grid");if(root)root.innerHTML=homeServices.filter(x=>x.featured).slice(0,8).map(s=>card(s,homeCategoryMap)).join("")}
function featuredCarousel(){const root=document.getElementById("featured-services-grid"),prev=document.getElementById("featured-services-prev"),next=document.getElementById("featured-services-next");if(!root||!prev||!next)return;const behavior=()=>window.matchMedia&&window.matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth";const max=()=>Math.max(0,root.scrollWidth-root.clientWidth);const update=()=>{prev.disabled=root.scrollLeft<=1;next.disabled=root.scrollLeft>=max()-1};const move=dir=>{const first=root.querySelector(".sf-service-card"),step=first?first.getBoundingClientRect().width+14:320;root.scrollTo({left:Math.max(0,Math.min(max(),root.scrollLeft+step*dir)),behavior:behavior()})};prev.addEventListener("click",()=>move(-1));next.addEventListener("click",()=>move(1));root.addEventListener("keydown",e=>{if(e.target!==root)return;if(e.key==="ArrowRight"||e.key==="ArrowLeft"){e.preventDefault();move(e.key==="ArrowRight"?1:-1)}else if(e.key==="Home"||e.key==="End"){e.preventDefault();root.scrollTo({left:e.key==="Home"?0:max(),behavior:behavior()})}});root.addEventListener("scroll",update,{passive:true});window.addEventListener("resize",update);update()}
function homeSearch(){const f=document.getElementById("home-service-search"),i=document.getElementById("home-service-query");if(!f||!i)return;f.addEventListener("submit",e=>{e.preventDefault();const q=i.value.trim();location.href=q?"/services?q="+encodeURIComponent(q):"/services"})}
function catalogue(){const grid=document.getElementById("service-catalog-grid");if(!grid)return;const input=document.getElementById("service-search"),reset=document.getElementById("service-search-reset"),count=document.getElementById("service-result-count"),empty=document.getElementById("service-empty-state"),params=new URLSearchParams(location.search),fixed=document.body.dataset.categoryPage||"",activeCategories=fixed?homeCategories:catalogCategories,activeServices=fixed?homeServices:catalogServices,activeMap=fixed?homeCategoryMap:catalogCategoryMap;let active=fixed||params.get("category")||"",query=params.get("q")||"";if(input)input.value=query;
const chips=document.getElementById("service-category-filters");if(active&&!activeCategories.some(c=>c.slug===active))active="";function syncChips(){if(chips)chips.querySelectorAll("button").forEach(x=>{const selected=x.dataset.category===active;x.classList.toggle("active",selected);x.setAttribute("aria-pressed",String(selected))})}if(chips&&!fixed){chips.innerHTML=['<button type="button" data-category="" aria-pressed="true" class="active">All services</button>',...activeCategories.map(c=>'<button type="button" data-category="'+escapeHtml(c.slug)+'" aria-pressed="false">'+escapeHtml(c.label)+'</button>')].join("");chips.addEventListener("click",e=>{const b=e.target.closest("button[data-category]");if(!b)return;active=b.dataset.category||"";syncChips();render()});syncChips()}
function render(){const n=query.trim().toLowerCase(),items=activeServices.filter(s=>matchesCategory(s,active)&&(!n||[s.title,s.description,s.meta,s.keywords,categoryFor(s,activeMap).label].join(" ").toLowerCase().includes(n)));grid.innerHTML=items.map(s=>card(s,activeMap)).join("");if(count)count.textContent=items.length+(items.length===1?" service":" services");if(empty)empty.hidden=items.length!==0;const url=new URL(location.href);if(query.trim())url.searchParams.set("q",query.trim());else url.searchParams.delete("q");if(active&&!fixed)url.searchParams.set("category",active);else url.searchParams.delete("category");history.replaceState(null,"",url.pathname+url.search+url.hash)}
if(input)input.addEventListener("input",()=>{query=input.value;render()});if(reset)reset.addEventListener("click",()=>{query="";active=fixed||"";if(input)input.value="";syncChips();render();if(input)input.focus()});render()}
function prefill(){if(!document.getElementById("client-inquiry-form"))return;const slug=new URLSearchParams(location.search).get("service"),s=catalogServices.find(x=>x.slug===slug)||homeServices.find(x=>x.slug===slug);if(!s)return;const summary=document.getElementById("project-summary");if(summary&&!summary.value.trim())summary.value="Selected service: "+s.title+"\n\nProject requirements:";const select=document.getElementById("project-category"),map={"trading-systems":"quantitative_finance","ai-llm":"ai_agentic_systems","business-automation":"ai_agentic_systems","web-saas":"web_mobile_dev","software-backend":"custom_enterprise","api-integrations":"cloud_microservices","data-scraping":"data_scraping_etl","cloud-devops":"cloud_microservices","bots-messaging":"web3_automation","ai-model-engineering":"ai_agentic_systems","seo-analytics":"web_mobile_dev","research-consulting":"custom_enterprise",trading:"quantitative_finance","ai-automation":"ai_agentic_systems",websites:"web_mobile_dev","software-apis":"cloud_microservices","cloud-support":"cloud_microservices"};if(select&&map[s.category])select.value=map[s.category]}
document.addEventListener("DOMContentLoaded",()=>{renderCategories();renderFeatured();featuredCarousel();homeSearch();catalogue();prefill()});
})();
