(function(){"use strict";
const data=window.NEXTGEN_SERVICE_CATALOG||{categories:[],services:[]},categoryMap=Object.fromEntries(data.categories.map(x=>[x.slug,x]));
const categoryFor=s=>categoryMap[s.category]||{label:"Custom Service"};
const matchesCategory=(s,slug)=>!slug||s.category===slug||(s.secondaryCategories||[]).includes(slug);
const card=s=>{const c=categoryFor(s),q="/?service="+encodeURIComponent(s.slug)+"#contact";return '<article class="sf-service-card"><a class="sf-service-main" href="'+s.href+'"><span class="sf-card-category">'+c.label+'</span><h3>'+s.title+'</h3><p>'+s.description+'</p><small>'+s.meta+'</small></a><div class="sf-service-actions"><a href="'+s.href+'">View service</a><a class="sf-quote-link" href="'+q+'">Request a quote</a></div></article>'};
function renderCategories(){document.querySelectorAll("[data-storefront-categories]").forEach(root=>root.innerHTML=data.categories.map(c=>'<a class="sf-category-card" href="'+c.url+'"><span>'+c.label+'</span><p>'+c.short+'</p><b>Explore <i aria-hidden="true">→</i></b></a>').join(""))}
function renderFeatured(){const root=document.getElementById("featured-services-grid");if(root)root.innerHTML=data.services.filter(x=>x.featured).slice(0,8).map(card).join("")}
function homeSearch(){const f=document.getElementById("home-service-search"),i=document.getElementById("home-service-query");if(!f||!i)return;f.addEventListener("submit",e=>{e.preventDefault();const q=i.value.trim();location.href=q?"/services?q="+encodeURIComponent(q):"/services"})}
function catalogue(){const grid=document.getElementById("service-catalog-grid");if(!grid)return;const input=document.getElementById("service-search"),reset=document.getElementById("service-search-reset"),count=document.getElementById("service-result-count"),empty=document.getElementById("service-empty-state"),params=new URLSearchParams(location.search),fixed=document.body.dataset.categoryPage||"";let active=fixed||params.get("category")||"",query=params.get("q")||"";if(input)input.value=query;
const chips=document.getElementById("service-category-filters");if(chips&&!fixed){chips.innerHTML=['<button type="button" data-category="" class="active">All services</button>',...data.categories.map(c=>'<button type="button" data-category="'+c.slug+'">'+c.label+'</button>')].join("");chips.addEventListener("click",e=>{const b=e.target.closest("button[data-category]");if(!b)return;active=b.dataset.category||"";chips.querySelectorAll("button").forEach(x=>x.classList.toggle("active",x===b));render()});const init=chips.querySelector('[data-category="'+active+'"]');if(init)chips.querySelectorAll("button").forEach(x=>x.classList.toggle("active",x===init))}
function render(){const n=query.trim().toLowerCase(),items=data.services.filter(s=>matchesCategory(s,active)&&(!n||[s.title,s.description,s.meta,s.keywords,categoryFor(s).label].join(" ").toLowerCase().includes(n)));grid.innerHTML=items.map(card).join("");if(count)count.textContent=items.length+(items.length===1?" service":" services");if(empty)empty.hidden=items.length!==0}
if(input)input.addEventListener("input",()=>{query=input.value;render()});if(reset)reset.addEventListener("click",()=>{query="";active=fixed||"";if(input)input.value="";if(chips)chips.querySelectorAll("button").forEach(x=>x.classList.toggle("active",!x.dataset.category));render();if(input)input.focus()});render()}
function prefill(){if(!document.getElementById("client-inquiry-form"))return;const slug=new URLSearchParams(location.search).get("service"),s=data.services.find(x=>x.slug===slug);if(!s)return;const summary=document.getElementById("project-summary");if(summary&&!summary.value.trim())summary.value="Selected service: "+s.title+"\n\nProject requirements:";const select=document.getElementById("project-category"),map={trading:"quantitative_finance","ai-automation":"ai_agentic_systems",websites:"web_mobile_dev","software-apis":"cloud_microservices","cloud-support":"cloud_microservices"};if(select&&map[s.category])select.value=map[s.category]}
document.addEventListener("DOMContentLoaded",()=>{renderCategories();renderFeatured();homeSearch();catalogue();prefill()});
})();